name: Hello-World

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: create file
        run : |
            mkdir santosh
            cd santosh
            touch file.py
            ls -l
            

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: SantoshMorla/tws-portfolio
          path: https://github.com/SantoshMorla/tws-portfolio/
        
      
    
    
